### ISSUE TITLE
Nothing shows up

### ISSUE THREAD

**Issue by Deleora** [sipspatidar/Instagram-Backup-Data-Viewer-Latest-Format#1]
Hi,

I followed exact same steps as described but when I open it on Firefox browser, nothing shows up. I only see the default items on their place holders but no messages or even my username and profile pic are shown.

I think it might be due the change in backup format provided by Instagram. Can you please look into this? 

Cheers!

**Comment by sipspatidar** [comment]
Try this 
in type about:config in your Firefox browser and then security.fileuri.strict_origin_policy and make it false

**Comment by Deleora** [comment]
It working!!
Thanks a lot
